pub const STANDARD_GRAVITY: f64 = 9.806_65;

/// Weight is the force generated by the gravitational attraction of one object on another object.
///
/// The weight equation: 𝑊=𝑚𝑔
/// ```
/// use physicist::weight;
///
/// let value = weight(11.0);
/// assert_eq!(value, 107.87315)
/// ```
///
/// https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/weight-equation-2/
pub fn weight(mass: f64) -> f64 {
    mass * STANDARD_GRAVITY
}

pub fn density(mass: f64, vol: f64) -> f64 {
    mass / vol
}

pub fn volume(length: f64, width: f64, height: f64) -> f64 {
    length * width * height
}

pub fn area(length: f64, width: f64) -> f64 {
    length * width
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let mass = 0.005;
        let expected_weight = 0.04903325;
        let result = weight(mass);

        assert_eq!(result, expected_weight);
    }
}
