name: ci

on:
  push:

env:
  CARGO_TERM_COLOR: always
  # https://doc.rust-lang.org/stable/clippy/continuous_integration/index.html
  RUSTFLAGS: -Dwarnings

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint (Clippy)
      run: cargo clippy
    
    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose
