name: ci

on:
    push:

env:
    CARGO_TERM_COLOR: always
    # https://doc.rust-lang.org/stable/clippy/continuous_integration/index.html
    RUSTFLAGS: -Dwarnings

jobs:
    lint_and_fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Lint (Clippy)
              run: cargo clippy

            - name: Format
              run: cargo fmt --all -- --check
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run tests
              run: cargo test --verbose

            # Might be moved
            - name: Build
              run: cargo build --verbose
